### ISSUE TITLE
Missing file Geometry.h

### ISSUE THREAD

**Issue by aluaces** [lakeweb/BXLReader#1]
https://github.com/lakeweb/BXLReader/blob/d6da7e7b75b7f48f37b5372a626e5b24b3d75fa3/stdafx.h#L54

It seems that this file holds the type definitions for "bg_point" and others, but is missing from the repo so it's not possible to build the project.

**Comment by aluaces** [comment]
Thanks, so I did, but I don't know if being related or not, the definitions of "bg_points" and other types are undefined.

Do they belong to any external library?

**Comment by lakeweb** [comment]
I'm not sure why you are seeing this. I've searched the project on my side and there is no 'bg_point' declared. I was using it before my first commit but decided not to burden this app with it. At the top of 'namespace Component' I have declared a simple geometry for stashing objects. It sounds like you are in an earlier commit, and yes, they do have a bg_point dependency. If you don't see a 'base_draw' struct at the top of BXL_Component.h, hit BXLReader and download the latest.
Best, Dan.

**Comment by aluaces** [comment]
Ok, sorry, I see it is corrected now.  I was just commenting the line as well, but without further modifications.

Now the build is stopped because `testing.h` does not exist:

https://github.com/lakeweb/BXLReader/blob/master/Main.cpp#L9

It seems it is defining some `in_Lines` function, because if I comment it out, I get a linker error for that reason.

**Comment by lakeweb** [comment]
Yes, I had added that file but did not add it to the repository. I've corrected that. Thank you for the notice. It is to evolve the spirit parser, I just have not had time to work on it.
Best, Dan.

**Comment by aluaces** [comment]
Now it is working.  Thanks a lot!
